# PyTorch Tutorial

## Tensor Basics

- In PyTorch everything is made using tensor structure;

In [1]:
#libraries

import torch
import numpy as np

In [4]:
x = torch.empty(1) #1d tensor
print(x)

tensor([1.4013e-45])


In [6]:
x = torch.empty(2,2,2) # 3d tensor
print(x)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


In [7]:
x = torch.rand(2,2) #random torch
print(x)

tensor([[0.4568, 0.4903],
        [0.1819, 0.3378]])


In [9]:
x = torch.ones(2,2,2) # 3d tensor by ones
print(x)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


In [10]:
x = torch.ones(2,2,dtype=torch.int) # type: int32, float32, double
print(x.dtype)

torch.int32


In [13]:
x = torch.ones(2,2,dtype=torch.int)
print(x.size()) # size 

torch.Size([2, 2])


### Basic Operations

In [17]:
# sum

x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

z = torch.add(x,y)
print(z)

y.add_(x)
print(y)

x tensor([[5.4717e-05, 1.8612e-01],
        [9.4204e-01, 7.7236e-01]])
tensor([[0.9126, 0.6349],
        [0.8317, 0.5188]])
tensor([[0.9127, 0.8210],
        [1.7737, 1.2912]])
tensor([[0.9127, 0.8210],
        [1.7737, 1.2912]])


In [18]:
# subtraction

z = torch.sub(x,y)
print(z)

tensor([[-0.9126, -0.6349],
        [-0.8317, -0.5188]])


In [23]:
# multiplication

z = torch.mul(x,y)
print(z)

y.mul_(x)
print(y)

tensor([[4.9940e-05, 1.5281e-01],
        [1.6709e+00, 9.9724e-01]])
tensor([[4.9940e-05, 1.5281e-01],
        [1.6709e+00, 9.9724e-01]])


In [24]:
# division

z = torch.div(x,y)
print(z)

tensor([[1.0957, 1.2180],
        [0.5638, 0.7745]])


In [37]:
# slicing

x = torch.rand(5,3)
print(x)
print(x[:,0]) # all rows and column 1
print(x[0,:]) # all columns and row 1
print(x[1,2]) # a single element in row 2 and column 3

tensor([[0.7590, 0.4619, 0.7571],
        [0.5250, 0.8471, 0.0761],
        [0.1872, 0.7240, 0.3796],
        [0.9982, 0.7962, 0.1752],
        [0.5392, 0.1406, 0.6960]])
tensor([0.7590, 0.5250, 0.1872, 0.9982, 0.5392])
tensor([0.7590, 0.4619, 0.7571])
tensor(0.0761)


In [45]:
# tensor to numpy

a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)
 

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### Cuda

In [46]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device = device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z = z.to("cpu")

## Autograd

In [ ]:
import torch

x = torch.rand(3, requires_grad=True)
print(x)