# Autograd

In [4]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.4411, -0.3046, -0.0339], requires_grad=True)


In [8]:
y = x + 2
print(y)

tensor([1.5589, 1.6954, 1.9661], grad_fn=<AddBackward0>)


In [10]:
z = y*y*2
z = z.mean()
print(z)

tensor(6.1135, grad_fn=<MeanBackward0>)


In [11]:
z.backward() #dz/dx
print(x.grad)

tensor([2.0786, 2.2606, 2.6214])


In [12]:
with torch.no_grad():
    y = x + 2
    print(y)

tensor([1.5589, 1.6954, 1.9661])


In [17]:
# dummy example

weights = torch.ones(4, requires_grad = True)

for epoch in range(10):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [25]:
#
x = torch.rand(3, requires_grad = True)

x.backward()
weights.grad.zero_()

RuntimeError: grad can be implicitly created only for scalar outputs